services:
  # Full Stack Application (Backend + Frontend)
  - type: web
    name: sales-automation-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: FB_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/health
